### ISSUE TITLE
Complete API Models

### ISSUE THREAD

**Issue by xacobecm** [Mariops99/OpenInventory#4]
I need @Mariops99 to complete the model fields, so I can complete the database planning.

**Comment by Mariops99** [comment]
Ok, so Products tablet needs 

-Barcode
-Description (Product name)
-Scan Date
-BrandName
-Model(Optional)
-FactoryReference (Optional) ((maybe this column can be mames as "part number", "skv"))
-lot
-DateofExpiry
-Reference (Optional)

**Comment by xacobecm** [comment]
Please specify also the Employee table's values so I can close this ticket. Thank you.

**Comment by Mariops99** [comment]
We must have another table like CompanyTable with the following columns
CompanyTable:
-ComanyName
-ListofEmployers
-Website


Employee table: 
-FullName
-CompanyName
-NationalIdentificationNumber
-email
-password

**Comment by xacobecm** [comment]
Thank you Mario. Closed.
